### ISSUE TITLE
NameError: name 'generate_config' is not defined

### ISSUE THREAD

**Issue by elizabethdinella** [crytic/echidna-parade#9]
Hi, I am attempting to run `echidna-parade` on one of my smart contracts. I am getting the following error.. 

```
Traceback (most recent call last):
  File "/home/edinella/.local/bin/echidna-parade", line 8, in <module>
    sys.exit(main())
  File "/home/edinella/.local/lib/python3.8/site-packages/echidna_parade/__main__.py", line 139, in main
    run_campaign(config)
  File "/home/edinella/.local/lib/python3.8/site-packages/echidna_parade/campaign.py", line 147, in run_campaign
    create_echidna_process(
  File "/home/edinella/.local/lib/python3.8/site-packages/echidna_parade/echidna.py", line 112, in create_echidna_process
    g = generate_echidna_config(
  File "/home/edinella/.local/lib/python3.8/site-packages/echidna_parade/echidna.py", line 80, in generate_echidna_config
    return generate_config(
NameError: name 'generate_config' is not defined
```

Error does not occur when I use the `examples/justlen` config and contract. So I am guessing there is something wrong with my particular contract and config. 

Here is my config: 

```
deployContracts: [["0xB3775fB83F7D12A36E0475aBdD1FCA35c091efBe", "Hourglass"]]
contractAddr: "0xc1FDdD8C8E57a10419A01b1aEC2f4F4F64A2393f"
codeSize: 0xffff
testMaxGas: 100000000000000
corpusDir: "cov/"
balanceContract: 0xfffffffffffffffffffffff
testMode: assertion
seqLen: 1
shrinkLimit: 1
testLimit: 10000
```

Contract is solc version 0.4.26

**Comment by elizabethdinella** [comment]
Solved by adding my single function to the `--always` flag and removing probabilistic exclusion. 

I'll leave this open since I don't see a `generate_config` function anywhere in the `echidna-parade` repo, but feel free to close if this is expected behavior.

**Comment by bsamuels453** [comment]
I think this issue is fixed on main
